// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnCZW9JdZBmWpYVo86V9iKA1mD3SG4wWM',
    appId: '1:93394305926:web:b715453923b912ca6c2207',
    messagingSenderId: '93394305926',
    projectId: 'priora-df8ba',
    authDomain: 'priora-df8ba.firebaseapp.com',
    storageBucket: 'priora-df8ba.firebasestorage.app',
    measurementId: 'G-SC75BEHT68',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsJxA0rgLQpv-1X2lFXs_gVkW3JuwaoeQ',
    appId: '1:93394305926:ios:7c2a1c2c45239ceb6c2207',
    messagingSenderId: '93394305926',
    projectId: 'priora-df8ba',
    storageBucket: 'priora-df8ba.firebasestorage.app',
    iosClientId: '93394305926-hh448tont9mft4ia71b1mt9j4105gdgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.priora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnCZW9JdZBmWpYVo86V9iKA1mD3SG4wWM',
    appId: '1:93394305926:web:50f18812f89148e06c2207',
    messagingSenderId: '93394305926',
    projectId: 'priora-df8ba',
    authDomain: 'priora-df8ba.firebaseapp.com',
    storageBucket: 'priora-df8ba.firebasestorage.app',
    measurementId: 'G-226VWNDJVL',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsJxA0rgLQpv-1X2lFXs_gVkW3JuwaoeQ',
    appId: '1:93394305926:ios:7c2a1c2c45239ceb6c2207',
    messagingSenderId: '93394305926',
    projectId: 'priora-df8ba',
    storageBucket: 'priora-df8ba.firebasestorage.app',
    iosClientId: '93394305926-hh448tont9mft4ia71b1mt9j4105gdgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.priora',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgGMRZeMfIbfGvpZPxagkF0imMUEyhTCw',
    appId: '1:93394305926:android:d0ec67b1cfe69e5f6c2207',
    messagingSenderId: '93394305926',
    projectId: 'priora-df8ba',
    storageBucket: 'priora-df8ba.firebasestorage.app',
  );
}
